ALTER TABLE users ADD COLUMN IF NOT EXISTS password_text VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS subscription_end_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP + INTERVAL '365 days';
